branches:
- "main"
- "master"
- "dev"
  prerelease: true
plugins:
- "@semantic-release/commit-analyzer"
- "@semantic-release/release-notes-generator"
- "@semantic-release/gitlab"
- - "@semantic-release/changelog"
  - changelogFile: CHANGELOG.md
- - "@semantic-release/git"
  - assets:
    - CHANGELOG.md
    message: |-
      chore(release): ${nextRelease.version} [skip ci]
      ${nextRelease.notes}
- - "@semantic-release/exec"
  - verifyReleaseCmd: "echo ${nextVersion.version} \n"
